# Site settings
title: Romain Bachelier
email: rollromin@yahoo.fr
url: https://github.com/Betshet
description: "Programmeur et Game designer"
keywords: "your keywords, separated by commas"
skills: "Programmeur - Game designer"
meta_author: Bachelier Romain

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:



# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Adresse
  social: Liens
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bluesky
    url: https://bsky.app/profile/betshet.bsky.social
  - title: itch
    url: https://betshet.itch.io/
  - title: github
    url: https://github.com/Betshet

# Postal address (add as many lines as necessary)
address:
  - line: 102 rue du Général Chanzy
  - line: 37000 Tours
  - line: France

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
